# Generated by Django 3.2.9 on 2021-11-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateTimeField(verbose_name='Дата рождения')),
                ('passport', models.CharField(max_length=20, verbose_name='Паспорт')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('mobile', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('second_mobile', models.CharField(max_length=150, verbose_name='Второй номер телефона')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('isu_number', models.IntegerField(verbose_name='Номер ИСУ')),
                ('vk_username', models.CharField(max_length=150, verbose_name='Vk')),
                ('login_name', models.CharField(max_length=50, verbose_name='Логин в системе N')),
                ('passwd_name', models.CharField(max_length=50, verbose_name='Пароль в системе N')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
