# Generated by Django 3.2.9 on 2021-11-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20211124_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='human',
            name='patronymic',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='human',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='human',
            name='second_mobile',
            field=models.CharField(max_length=150, null=True, verbose_name='Второй номер телефона'),
        ),
    ]
