# Generated by Django 3.2.9 on 2021-11-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20211124_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='human',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='human',
            name='second_mobile',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Второй номер телефона'),
        ),
    ]
