# Generated by Django 3.2.9 on 2021-11-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20211124_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sec_name',
        ),
        migrations.AddField(
            model_name='human',
            name='seccat',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seccat', to='people.category'),
        ),
        migrations.AlterField(
            model_name='human',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat', to='people.category'),
        ),
    ]
