# Generated by Django 3.2.9 on 2021-11-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20211124_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='people.category'),
        ),
        migrations.AlterField(
            model_name='human',
            name='seccat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SecondCategory', to='people.category'),
        ),
    ]
