# Generated by Django 3.2.9 on 2021-11-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20211124_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='fourcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FourthCategory', to='people.category'),
        ),
        migrations.AddField(
            model_name='human',
            name='thirdcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ThirdCategory', to='people.category'),
        ),
    ]
