# Generated by Django 3.2.9 on 2021-11-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20211124_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='fourcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FourthCategory', to='people.category'),
        ),
        migrations.AlterField(
            model_name='human',
            name='seccat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SecondCategory', to='people.category'),
        ),
        migrations.AlterField(
            model_name='human',
            name='thirdcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ThirdCategory', to='people.category'),
        ),
    ]
