# Generated by Django 3.2.9 on 2021-11-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20211124_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
